name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  provider: ^6.0.5
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  easy_localization: ^3.0.2
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  sizer: ^2.0.15
  go_router: ^10.0.0
  shared_preferences: ^2.2.0
  pretty_dio_logger: ^1.3.1
  git_hooks: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
